single : True
rrt/max_failed_attemptes : 10000
rrt/t_max : 8
rrt/s_max : 60
rrt/t_goal : 5
rrt/v_goal : 10
rrt/dt : 0.1
rrt/max_acc : 5
rrt/max_vel : 15
rrt/kr : 1
rrt/ks : 1
rrt/kv : 2
rrt/lower_range_t : 1
rrt/lower_range_s : 10
rrt/upper_range_t : 1
rrt/upper_range_s : 10
rrt/upper_range_a: 0.5
rrt/lower_range_a: 0.5

rrt/k_risk : 10
rrt/danger_distance : 10
rrt/safe_distance : 50
rrt/car_width : 3

# case : "emergency_stop", "crossing intersection", "keep lane"
single_test/single_test_case: 'emergency_stop'
single_test/collision_number: 1
emergency_stop_case/x0: 400
emergency_stop_case/y0: 502.5
emergency_stop_case/theta0 : 4.712
emergency_stop_case/v0: 10
emergency_stop_case/obs1_x0: 360
emergency_stop_case/obs1_y0: 502.5
emergency_stop_case/obs1_theta0: 4.712
emergency_stop_case/obs1_v0: 0
