single : True
rrt/max_failed_attemptes : 10000
rrt/t_max : 5
rrt/s_max : 60
rrt/t_goal : 3
rrt/v_goal : 10
rrt/dt : 0.1
rrt/max_acc : 10
rrt/max_vel : 15
rrt/kr : 1
rrt/ks : 1
rrt/kv : 2
rrt/lower_range_t : 1
rrt/lower_range_s : 10
rrt/upper_range_t : 1
rrt/upper_range_s : 10
rrt/upper_range_a: 0.5
rrt/lower_range_a: 0.5

rrt/k_risk : 10
rrt/danger_distance : 10
rrt/safe_distance : 50
rrt/car_width : 3

single_test/single_test_case : 'keep_lane_case'
single_test/collision_number : 2

emergency_stop_case/x0 : 520
emergency_stop_case/y0 : 497.5
emergency_stop_case/theta0 : 1.570
emergency_stop_case/v0 : 10
emergency_stop_case/obs1_x0 : 550
emergency_stop_case/obs1_y0 : 497.5
emergency_stop_case/obs1_theta0 : 1.570
emergency_stop_case/obs1_v0 : 0

croosing_case/x0 : 400
croosing_case/y0 : 502.5
croosing_case/theta0 : 4.712
croosing_case/v0 : 10
croosing_case/obs1_x0 : 360
croosing_case/obs1_y0 : 502.5
croosing_case/obs1_theta0 : 4.712
croosing_case/obs1_v0 : 0

keep_lane_case/x0 : 540
keep_lane_case/y0 : 497.5
keep_lane_case/theta0 : 1.570
keep_lane_case/v0 : 10
keep_lane_case/obs1_x0 : 520
keep_lane_case/obs1_y0 : 497.5
keep_lane_case/obs1_theta0 : 1.570
keep_lane_case/obs1_v0 : 11
keep_lane_case/obs2_x0 : 570
keep_lane_case/obs2_y0 : 497.5
keep_lane_case/obs2_theta0 : 1.570
keep_lane_case/obs2_v0 : 12




