single : True
rrt/max_failed_attemptes : 10000
rrt/t_max : 5
rrt/s_max : 60
rrt/t_goal : 3
rrt/v_goal : 10
rrt/dt : 0.1
rrt/max_acc : 10
rrt/max_vel : 15
rrt/kr : 1
rrt/ks : 1
rrt/kv : 2
rrt/lower_range_t : 1
rrt/lower_range_s : 10
rrt/upper_range_t : 1
rrt/upper_range_s : 10
rrt/upper_range_a: 0.5
rrt/lower_range_a: 0.5

rrt/k_risk : 10
rrt/danger_distance : 10
rrt/safe_distance : 50
rrt/car_width : 3

single_test/x0 : 502.55
single_test/y0 : 484.8
single_test/theta0 : 0
single_test/s0 : 0.6
single_test/v0 : 6

single_test/obs1_x0 : 502.55
single_test/obs1_y0 : 460
single_test/obs1_theta0 : 0
single_test/obs1_v0 : 0

single_test/obs2_x0 : 505.5
single_test/obs2_y0 : 502.5
single_test/obs2_theta0 : 4.712
single_test/obs2_v0 : 8
