rrt/max_failed_attemptes : 10000
rrt/t_max : 5
rrt/s_max : 60
rrt/t_goal : 3
rrt/s_goal : 20
rrt/v_goal : 10
rrt/dt : 0.2
rrt/max_acc : 4
rrt/max_vel : 12
rrt/kr : 1
rrt/ks : 1
rrt/kv : 1
rrt/lower_range_t : 1
rrt/lower_range_s : 10
rrt/upper_range_t : 1
rrt/upper_range_s : 10
rrt/k_risk : 10
rrt/danger_distance : 10
rrt/safe_distance : 50
rrt/car_width : 3
