# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planning/ObstacleMap.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import planning.msg

class ObstacleMap(genpy.Message):
  _md5sum = "53002d3079c88d059fd08d0aaa769907"
  _type = "planning/ObstacleMap"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """DynamicObstacle[] dynamic_obstacles
================================================================================
MSG: planning/DynamicObstacle
uint64 timestamp
string id
float64 x
float64 y
float64 theta
float64 velocity"""
  __slots__ = ['dynamic_obstacles']
  _slot_types = ['planning/DynamicObstacle[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dynamic_obstacles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleMap, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dynamic_obstacles is None:
        self.dynamic_obstacles = []
    else:
      self.dynamic_obstacles = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.dynamic_obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obstacles:
        buff.write(_struct_Q.pack(val1.timestamp))
        _x = val1.id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.theta, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.dynamic_obstacles is None:
        self.dynamic_obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obstacles = []
      for i in range(0, length):
        val1 = planning.msg.DynamicObstacle()
        start = end
        end += 8
        (val1.timestamp,) = _struct_Q.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.id = str[start:end].decode('utf-8')
        else:
          val1.id = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.theta, _x.velocity,) = _struct_4d.unpack(str[start:end])
        self.dynamic_obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.dynamic_obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obstacles:
        buff.write(_struct_Q.pack(val1.timestamp))
        _x = val1.id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.theta, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.dynamic_obstacles is None:
        self.dynamic_obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obstacles = []
      for i in range(0, length):
        val1 = planning.msg.DynamicObstacle()
        start = end
        end += 8
        (val1.timestamp,) = _struct_Q.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.id = str[start:end].decode('utf-8')
        else:
          val1.id = str[start:end]
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.theta, _x.velocity,) = _struct_4d.unpack(str[start:end])
        self.dynamic_obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Q = struct.Struct("<Q")
_struct_4d = struct.Struct("<4d")
