function debug_file_config = readDebugFile( ReadFromData, scene)
%UNTITLED 此处显示有关此函数的摘要
%   此处显示详细说明
file_name = [ {'road_file_locate'}; ...
              {'test_config_file_locate'}; ...
              {'distance_map_config_locate'}; ...
              {'distance_map_locate'}; ...
              {'rrt_debug_locate'}];
          
if ReadFromData
    file_locate = [{['./new-result/', scene, '_path.txt']}; ...
                   {['./new-result/', scene, '_test_config.pb.txt']}; ...
                   {['./new-result/', scene, '_distance_map_dbg.pb.txt']};...
                   {['./new-result/', scene, '_distance_map.txt']};...
                   {['./new-result/', scene, '_rrt.txt']}];
else
    file_locate = [{['../../../simulation/data/path/','change_lane_path.txt']};...
                   {['../../config/',scene, '_test_config.pb.txt']};...
                   {'../../log/distance_map_dbg.pb.txt'};...
                   {'../../log/distance_map.txt'};...
                   {'../../log/rrt.txt'}];    
end

debug_file_config = containers.Map(file_name, file_locate);

end

